#!/usr/bin/env bash

set -u

ROOT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
LIB_DIR="$ROOT_DIR/lib"
DIST_DIR="$ROOT_DIR/dist"
OUTPUT="$DIST_DIR/dbtune"
CHECKSUM="$OUTPUT.sha256"

fail() {
    printf 'build: %s\n' "$*" >&2
    exit 1
}

append_embedded_files() {
    local output=$1
    local directory file relative encoded
    local found=0

    {
        printf '\n# Embedded project assets. Generated by build.sh.\n'
        printf 'dbtune_embedded_list() {\n'
        for directory in templates systemd; do
            [[ -d $ROOT_DIR/$directory ]] || continue
            for file in "$ROOT_DIR/$directory"/*; do
                [[ -f $file ]] || continue
                relative="$directory/${file##*/}"
                printf "    printf '%%s\\n' '%s'\n" "$relative"
                found=1
            done
        done
        ((found)) || printf '    :\n'
        printf '}\n\n'
        printf 'dbtune_base64_decode() {\n'
        printf '    if base64 --decode </dev/null >/dev/null 2>&1; then base64 --decode; else base64 -D; fi\n'
        printf '}\n\n'
        printf "dbtune_embedded_get() {\n    case \${1:-} in\n"
        for directory in templates systemd; do
            [[ -d $ROOT_DIR/$directory ]] || continue
            for file in "$ROOT_DIR/$directory"/*; do
                [[ -f $file ]] || continue
                relative="$directory/${file##*/}"
                encoded=$(base64 <"$file" | tr -d '\n') || return 1
                printf "        '%s') printf '%%s' '%s' | dbtune_base64_decode ;;\n" "$relative" "$encoded"
            done
        done
        printf "        *) printf 'Unknown embedded asset: %%s\\n' \"\${1:-}\" >&2; return 64 ;;\n"
        printf '    esac\n}\n'
    } >>"$output"
}

build() {
    local temporary module
    local -a modules

    [[ -d $LIB_DIR ]] || fail "lib directory is missing"
    mkdir -p "$DIST_DIR" || fail "cannot create dist directory"
    temporary=$(mktemp "$DIST_DIR/.dbtune.tmp.XXXXXX") || fail "mktemp failed"
    trap 'rm -f "$temporary"' EXIT

    mapfile -t modules < <(find "$LIB_DIR" -maxdepth 1 -type f -name '*.sh' -print | LC_ALL=C sort)
    ((${#modules[@]})) || fail "no lib modules found"
    [[ ${modules[0]} == "$LIB_DIR/00-header.sh" ]] || fail "first module must be lib/00-header.sh"
    [[ ${modules[${#modules[@]} - 1]} == "$LIB_DIR/90-main.sh" ]] || fail "last module must be lib/90-main.sh"

    command cat "${modules[0]}" >"$temporary" || fail "failed to write header"
    append_embedded_files "$temporary" || fail "failed to embed assets"
    for module in "${modules[@]:1}"; do
        printf '\n' >>"$temporary"
        command cat "$module" >>"$temporary" || fail "failed to write $module"
    done
    chmod 755 "$temporary" || fail "chmod failed"
    bash -n "$temporary" || fail "bash -n failed"
    if command -v shellcheck >/dev/null 2>&1; then
        shellcheck -s bash "$temporary" || fail "shellcheck failed"
    else
        printf 'build: shellcheck is not available, skipping\n' >&2
    fi
    bash -c '
        source "$1"
        for function_name in cmd_audit cmd_collect cmd_tick cmd_analyze cmd_report cmd_propose cmd_apply cmd_verify cmd_rollback cmd_status; do
            declare -F "$function_name" >/dev/null || exit 1
        done
        for asset in templates/tuning.cnf.tmpl systemd/dbtune-collect.service systemd/dbtune-collect.timer; do
            dbtune_embedded_get "$asset" >/dev/null || exit 1
        done
    ' _ "$temporary" || fail "artifact does not contain all commands and embedded assets"
    mv -f "$temporary" "$OUTPUT" || fail "failed to publish artifact"
    trap - EXIT

    if command -v sha256sum >/dev/null 2>&1; then
        (cd "$DIST_DIR" && sha256sum dbtune >dbtune.sha256) || fail "sha256sum failed"
    elif command -v shasum >/dev/null 2>&1; then
        (cd "$DIST_DIR" && shasum -a 256 dbtune >dbtune.sha256) || fail "shasum failed"
    else
        fail "neither sha256sum nor shasum is available"
    fi
    printf 'build: %s\n' "$OUTPUT"
    printf 'build: %s\n' "$CHECKSUM"
}

build "$@"
