#!/usr/bin/env bash

set -u

ROOT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
LIB_DIR="$ROOT_DIR/lib"
DIST_DIR="$ROOT_DIR/dist"
OUTPUT="$DIST_DIR/dbtune"
CHECKSUM="$OUTPUT.sha256"

fail() {
    printf 'build: %s\n' "$*" >&2
    exit 1
}

profile=production
case $# in
    0) ;;
    2)
        [[ $1 == --profile ]] || fail "unknown argument: $1"
        profile=$2
        ;;
    *) fail "usage: build.sh [--profile production|integration-test]" ;;
esac
case $profile in
    production|integration-test) ;;
    *) fail "unsupported profile: $profile" ;;
esac
if [[ $profile == integration-test ]]; then
    OUTPUT="$DIST_DIR/dbtune-integration"
    CHECKSUM=
fi

append_embedded_files() {
    local output=$1
    local directory file relative encoded
    local found=0

    {
        printf '\n# Embedded project assets. Generated by build.sh.\n'
        printf 'dbtune_embedded_list() {\n'
        for directory in templates systemd; do
            [[ -d $ROOT_DIR/$directory ]] || continue
            for file in "$ROOT_DIR/$directory"/*; do
                [[ -f $file ]] || continue
                relative="$directory/${file##*/}"
                printf "    printf '%%s\\n' '%s'\n" "$relative"
                found=1
            done
        done
        ((found)) || printf '    :\n'
        printf '}\n\n'
        printf 'dbtune_base64_decode() {\n'
        printf '    if base64 --decode </dev/null >/dev/null 2>&1; then base64 --decode; else base64 -D; fi\n'
        printf '}\n\n'
        printf "dbtune_embedded_get() {\n    case \${1:-} in\n"
        for directory in templates systemd; do
            [[ -d $ROOT_DIR/$directory ]] || continue
            for file in "$ROOT_DIR/$directory"/*; do
                [[ -f $file ]] || continue
                relative="$directory/${file##*/}"
                encoded=$(base64 <"$file" | tr -d '\n') || return 1
                printf "        '%s') printf '%%s' '%s' | dbtune_base64_decode ;;\n" "$relative" "$encoded"
            done
        done
        printf "        *) printf 'Unknown embedded asset: %%s\\n' \"\${1:-}\" >&2; return 64 ;;\n"
        printf '    esac\n}\n'
    } >>"$output"
}

validate_test_artifact() {
    bash -c '
        source "$1"
        for function_name in cmd_audit cmd_collect cmd_tick cmd_analyze cmd_report cmd_propose cmd_apply cmd_verify cmd_rollback cmd_status; do
            declare -F "$function_name" >/dev/null || exit 1
        done
        for asset in templates/tuning.cnf.tmpl systemd/dbtune-collect.service systemd/dbtune-collect.timer; do
            dbtune_embedded_get "$asset" >/dev/null || exit 1
        done
    ' _ "$1"
}

build() {
    local temporary checksum_temporary='' validation_temporary='' module function_name alternate
    local version_output version_status=0
    local -a modules

    [[ -d $LIB_DIR ]] || fail "lib directory is missing"
    mkdir -p "$DIST_DIR" || fail "cannot create dist directory"
    temporary=$(mktemp "$DIST_DIR/.dbtune.tmp.XXXXXX") || fail "mktemp failed"
    trap 'rm -f "$temporary" "$checksum_temporary" "$validation_temporary"' EXIT

    mapfile -t modules < <(find "$LIB_DIR" -maxdepth 1 -type f -name '*.sh' -print | LC_ALL=C sort)
    ((${#modules[@]})) || fail "no lib modules found"
    [[ ${modules[0]} == "$LIB_DIR/00-header.sh" ]] || fail "first module must be lib/00-header.sh"
    [[ ${modules[${#modules[@]} - 1]} == "$LIB_DIR/90-main.sh" ]] || fail "last module must be lib/90-main.sh"

    awk -v profile="$profile" '
        $0 == "readonly DBTUNE_ARTIFACT_PROFILE=source-test" {
            print "readonly DBTUNE_ARTIFACT_PROFILE=" profile
            next
        }
        $0 == "if [[ $DBTUNE_ARTIFACT_PROFILE != source-test ]]; then" {
            print "if [[ $DBTUNE_ARTIFACT_PROFILE != " profile " ]]; then"
            next
        }
        { print }
    ' "${modules[0]}" >"$temporary" || fail "failed to write header"
    append_embedded_files "$temporary" || fail "failed to embed assets"
    for module in "${modules[@]:1}"; do
        printf '\n' >>"$temporary"
        command cat "$module" >>"$temporary" || fail "failed to write $module"
    done
    chmod 755 "$temporary" || fail "chmod failed"
    [[ $(grep -c "^readonly DBTUNE_ARTIFACT_PROFILE=$profile$" "$temporary") == 1 ]] ||
        fail "artifact profile marker is missing or duplicated"
    for alternate in source-test production integration-test; do
        [[ $alternate == "$profile" ]] && continue
        ! grep -q "^readonly DBTUNE_ARTIFACT_PROFILE=$alternate$" "$temporary" ||
            fail "artifact contains an alternate profile marker"
    done
    bash -n "$temporary" || fail "bash -n failed"
    if command -v shellcheck >/dev/null 2>&1; then
        shellcheck -s bash "$temporary" || fail "shellcheck failed"
    else
        printf 'build: shellcheck is not available, skipping\n' >&2
    fi
    if [[ $profile == production ]]; then
        version_output=$(bash "$temporary" version) || version_status=$?
        [[ $version_status == 0 && $version_output == "dbtune 0.4.1" ]] ||
            fail "artifact version self-test failed (status $version_status)"
        for function_name in cmd_audit cmd_collect cmd_tick cmd_analyze cmd_report cmd_propose cmd_apply cmd_verify cmd_rollback cmd_status; do
            grep -q "^${function_name}()" "$temporary" || fail "artifact is missing $function_name"
        done
        validation_temporary=$(mktemp "$DIST_DIR/.dbtune-validation.tmp.XXXXXX") || fail "validation mktemp failed"
        awk '
            $0 == "readonly DBTUNE_ARTIFACT_PROFILE=production" {
                print "readonly DBTUNE_ARTIFACT_PROFILE=integration-test"
                next
            }
            $0 == "if [[ $DBTUNE_ARTIFACT_PROFILE != production ]]; then" {
                print "if [[ $DBTUNE_ARTIFACT_PROFILE != integration-test ]]; then"
                next
            }
            { print }
        ' "$temporary" >"$validation_temporary" || fail "failed to create test-profile validation artifact"
        chmod 755 "$validation_temporary" || fail "validation chmod failed"
        validate_test_artifact "$validation_temporary" || fail "artifact embedded asset validation failed"
        rm -f "$validation_temporary"
        validation_temporary=
        checksum_temporary=$(mktemp "$DIST_DIR/.dbtune.sha256.tmp.XXXXXX") || fail "checksum mktemp failed"
        if command -v sha256sum >/dev/null 2>&1; then
            sha256sum "$temporary" | awk '{print $1 "  dbtune"}' >"$checksum_temporary" || fail "sha256sum failed"
        elif command -v shasum >/dev/null 2>&1; then
            shasum -a 256 "$temporary" | awk '{print $1 "  dbtune"}' >"$checksum_temporary" || fail "shasum failed"
        else
            fail "neither sha256sum nor shasum is available"
        fi
    else
        validate_test_artifact "$temporary" || fail "artifact does not contain all commands and embedded assets"
    fi
    mv -f "$temporary" "$OUTPUT" || fail "failed to publish artifact"
    [[ -z $checksum_temporary ]] || mv -f "$checksum_temporary" "$CHECKSUM" || fail "failed to publish checksum"
    trap - EXIT
    printf 'build: %s\n' "$OUTPUT"
    [[ -z $CHECKSUM ]] || printf 'build: %s\n' "$CHECKSUM"
}

build "$@"
